#!/usr/bin/env bash

set -e

snapctl set usb-path="/dev/ttyACM0"
snapctl set stop-on-failure=true

snapctl set mqtt.server=localhost
snapctl set mqtt.port=1883
snapctl set mqtt.username=false
snapctl set mqtt.password=false
snapctl set mqtt.connect-timeout=30
snapctl set mqtt.tls=false

snapctl set ozw.instance=1
snapctl set ozw.network-key="$(cat /dev/urandom | LC_ALL=C tr -dc '0-9A-F' | fold -w 32 | head -n 1 | sed -e 's/\(..\)/0x\1,/g' -e 's/,$//')"
snapctl set ozw.config-dir="${SNAP_DATA}/config"
snapctl set ozw.user-dir="${SNAP_DATA}/user"
snapctl set ozw.auth-key=""

mkdir "${SNAP_DATA}/config"
mkdir "${SNAP_DATA}/user"

snapctl stop --disable "${SNAP_NAME}.${SNAP_NAME}"
