name: ozwdaemon
base: core20
version: '0.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel
confinement: devmode

plugs:
  docker-executables:
    interface: content
    target: $SNAP/docker-snap
    default-provider: docker

apps:
   ozwdaemon:
     command: bin/wrapper
     plugs: 
      - network
      - docker

parts:
  ozwdaemon:
    plugin: dump
    source: src/
    organize:
      wrapper: bin/
      hooks: snap/hooks
